/*******************************************************************************
 *  Summary         : Test class for BatchDelExpQuoteAssoWOpenOpty
 *  Refer Object    : 
 *  Author          : Scott
 *  RefactorDate    : 12 Dec 2016
 *  Change Log      : Refactoring by SF-2.6 release, this class no longer use
 ******************************************************************************/
@isTest
private class BatchDelExpQuoteAssoWOpenOptyTest {
    
    @isTest static void test_method_one() {

        // no longer use
        //Test.startTest();
        // TestClassUtility.createTaskCreationSettingsWithQuoteDeleted(true);
        // Test.startTest();
        // Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects();
        // Test.stopTest();

        // // generate data needed by the test class
        // Opportunity testOpportunity = (Opportunity)testObjects.get('Opportunity');
        // testOpportunity.Opportunity_Expiration_Date__c = date.today().adddays(-1); 
        // update testOpportunity;

        // SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
        //                                          'Complete',
        //                                          '{"companyName": "Test Account"}',
        //                                          null);
        // Test.setMock(HttpCalloutMock.class, fakeResponse);        

        // BatchDelExpQuoAssWOpenOptyScheduleJob job = new BatchDelExpQuoAssWOpenOptyScheduleJob();
        // String sch = '0 1 0 * * ?';
        // System.schedule('Test BatchDelExpQuoAssWOpenOptyScheduleJob Job', sch, job);
        
    }
}