@isTest
private class BatchUpdateAcctMarketSaleabilityTest {

    //Comment by CSP-2712 Decommission Marketplace Health code
    // static testMethod void testMethod1() {
    //     Test.startTest();

    //     	Zip__c testZip = TestClassUtility.createzip(true);

    //     	Category__c testCategory = TestClassUtility.createCategory(false);
    //     	testCategory.Category_Code__c = 'ACC';
    //     	insert testCategory;

	   //      Account testAcct = TestClassUtility.createAccount(false);
	   //      testAcct.BillingPostalCode = testZip.ZipCode__c;
	   //      testAcct.Primary_Category__c = testCategory.id;
	   //      insert testAcct;

	   //      Marketplace_Health__c  testMS = new Marketplace_Health__c();
	   //      testMS.Category__c = testCategory.Id;
	   //      testMS.Zip__c = testZip.Id;
	   //      testMS.External_Key__c = testZip.ZipCode__c + testCategory.Category_Code__c;
	   //      insert testMS;

    //     	//Excute batch for update account market saleability 
    //     	BatchUpdateAcctMarketSaleability cls = new BatchUpdateAcctMarketSaleability();
    //     	Database.executeBatch(cls,2000);


    //     Test.stopTest();
    // }
}