// CLASS STRUCTURE
/* 
<class>
	<name></name>
	<purpose></purpose>
	<created>
		<purpose></purpose>
		<by></by>
		<date></date>
		<ticket></ticket>
	</created>
	<updates>
		<updated>
			<purpose></purpose>
			<by></by>
			<date></date>
			<ticket></ticket>
		</updated>
	</updates>
</class>
*/


// TRIGGER STRUCTURE
/*
<trigger>
	<name></name>
	<purpose></purpose>
	<created>
		<purpose></purpose>
		<by></by>
		<date></date>
		<ticket></ticket>
	</created>
	<updates>
		<updated>
			<purpose></purpose>
			<by></by>
			<date></date>
			<ticket></ticket>
		</updated>
	</updates>
</trigger>
*/


// METHOD STRUCTURE
/* 
<method>
	<name></name>
	<returns></returns>
	<purpose></purpose>
	<params>
		<param>
			<name></name>
			<purpose></purpose>
		</param>
	</params>
	<created>
		<purpose></purpose>
		<by></by>
		<date></date>
		<ticket></ticket>
	</created>
	<updates>
		<updated>
			<purpose></purpose>
			<by></by>
			<date></date>
			<ticket></ticket>
		</updated>
	</updates>
</method>
*/
public with sharing class META_xmlCommentStructure {

}