@isTest
private class objectApiZuoraComTest{
    @isTest static void test_method_one() {
        objectApiZuoraCom.InvoicePayment InvoicePayment = new objectApiZuoraCom.InvoicePayment();
        objectApiZuoraCom.Import_x Import_x = new objectApiZuoraCom.Import_x();
        objectApiZuoraCom.AccountingCode AccountingCode = new objectApiZuoraCom.AccountingCode();
        objectApiZuoraCom.AccountingPeriod AccountingPeriod = new objectApiZuoraCom.AccountingPeriod();
        objectApiZuoraCom.Account Account = new objectApiZuoraCom.Account();
        objectApiZuoraCom.InvoiceItem InvoiceItem = new objectApiZuoraCom.InvoiceItem();
        objectApiZuoraCom.InvoiceItemAdjustment InvoiceItemAdjustment = new objectApiZuoraCom.InvoiceItemAdjustment();
        objectApiZuoraCom.RefundInvoicePayment RefundInvoicePayment = new objectApiZuoraCom.RefundInvoicePayment();
        objectApiZuoraCom.Payment Payment = new objectApiZuoraCom.Payment();
        objectApiZuoraCom.Usage Usage = new objectApiZuoraCom.Usage();
        objectApiZuoraCom.RefundTransactionLog RefundTransactionLog = new objectApiZuoraCom.RefundTransactionLog();
        objectApiZuoraCom.InvoiceFile InvoiceFile = new objectApiZuoraCom.InvoiceFile();
        objectApiZuoraCom.ProductRatePlanCharge ProductRatePlanCharge = new objectApiZuoraCom.ProductRatePlanCharge();
        objectApiZuoraCom.Amendment Amendment = new objectApiZuoraCom.Amendment();
        objectApiZuoraCom.CommunicationProfile CommunicationProfile = new objectApiZuoraCom.CommunicationProfile();
        objectApiZuoraCom.PaymentTransactionLog PaymentTransactionLog = new objectApiZuoraCom.PaymentTransactionLog();
        objectApiZuoraCom.GatewayOption GatewayOption = new objectApiZuoraCom.GatewayOption();
        objectApiZuoraCom.InvoiceSplitItem InvoiceSplitItem = new objectApiZuoraCom.InvoiceSplitItem();
        objectApiZuoraCom.ProductRatePlan ProductRatePlan = new objectApiZuoraCom.ProductRatePlan();
        objectApiZuoraCom.ProductRatePlanChargeTier ProductRatePlanChargeTier = new objectApiZuoraCom.ProductRatePlanChargeTier();
        objectApiZuoraCom.PaymentMethodSnapshot PaymentMethodSnapshot = new objectApiZuoraCom.PaymentMethodSnapshot();
        objectApiZuoraCom.RatePlanCharge RatePlanCharge = new objectApiZuoraCom.RatePlanCharge();
        objectApiZuoraCom.RatePlan RatePlan = new objectApiZuoraCom.RatePlan();
        objectApiZuoraCom.Product Product = new objectApiZuoraCom.Product();
        objectApiZuoraCom.CreditBalanceAdjustment CreditBalanceAdjustment = new objectApiZuoraCom.CreditBalanceAdjustment();
        objectApiZuoraCom.Contact Contact = new objectApiZuoraCom.Contact();
        objectApiZuoraCom.Invoice Invoice = new objectApiZuoraCom.Invoice();
        objectApiZuoraCom.PaymentMethod PaymentMethod = new objectApiZuoraCom.PaymentMethod();
        objectApiZuoraCom.Export_x Export_x = new objectApiZuoraCom.Export_x();
        objectApiZuoraCom.InvoiceSplit InvoiceSplit = new objectApiZuoraCom.InvoiceSplit();
        objectApiZuoraCom.PaymentMethodTransactionLog PaymentMethodTransactionLog = new objectApiZuoraCom.PaymentMethodTransactionLog();
        objectApiZuoraCom.Subscription Subscription = new objectApiZuoraCom.Subscription();
        objectApiZuoraCom.RatePlanChargeTier RatePlanChargeTier = new objectApiZuoraCom.RatePlanChargeTier();
        objectApiZuoraCom.Refund Refund = new objectApiZuoraCom.Refund();
        objectApiZuoraCom.zObject zObject = new objectApiZuoraCom.zObject();

        
    }
}