@isTest
private class OperativeOneResponseWrapperTest {
    static testMethod void testMethodOne() {
        OperativeOneResponseWrapper operativeOneResponseWrapperTest = new OperativeOneResponseWrapper();
        OperativeOneResponseWrapper.SalesOrderWrapper salesOrderWrapperTest = new OperativeOneResponseWrapper.SalesOrderWrapper();
        OperativeOneResponseWrapper.ObjectNameWrapper objectNameWrapperTest = new OperativeOneResponseWrapper.ObjectNameWrapper();
        OperativeOneResponseWrapper.CustomFieldsWrapper customFieldsWrapperTestTest = new OperativeOneResponseWrapper.CustomFieldsWrapper();
        OperativeOneResponseWrapper.CustomFieldWrapper customFieldWrapperTest = new OperativeOneResponseWrapper.CustomFieldWrapper();
        OperativeOneResponseWrapper.SalesStageWrapper salesStageWrapperTest = new OperativeOneResponseWrapper.SalesStageWrapper();
        OperativeOneResponseWrapper.AccountsWrapper accountsWrapperTest = new OperativeOneResponseWrapper.AccountsWrapper();
        OperativeOneResponseWrapper.AccountWrapper accountWrapperTest = new OperativeOneResponseWrapper.AccountWrapper();
        OperativeOneResponseWrapper.RolesWrapper rolesWrapperTest = new OperativeOneResponseWrapper.RolesWrapper();
        OperativeOneResponseWrapper.RoleWrapper roleWrapperTest = new OperativeOneResponseWrapper.RoleWrapper();
        OperativeOneResponseWrapper.ContactsWrapper contactsWrapperTest = new OperativeOneResponseWrapper.ContactsWrapper();
        OperativeOneResponseWrapper.CrmSystemWrapper crmSystemWrapperTest = new OperativeOneResponseWrapper.CrmSystemWrapper();
        OperativeOneResponseWrapper.UsersWrapper usersWrapperTest = new OperativeOneResponseWrapper.UsersWrapper();
        OperativeOneResponseWrapper.UserWrapper userWrapperTest = new OperativeOneResponseWrapper.UserWrapper();
        OperativeOneResponseWrapper.SalesOpportunityWrapper salesOpportunityWrapperTest = new OperativeOneResponseWrapper.SalesOpportunityWrapper();
        OperativeOneResponseWrapper.LineitemDiscountsWrapper lineitemDiscountsWrapperTest = new OperativeOneResponseWrapper.LineitemDiscountsWrapper();
        OperativeOneResponseWrapper.DiscountsWrapper discountsWrapperTest = new OperativeOneResponseWrapper.DiscountsWrapper();
        OperativeOneResponseWrapper.MediaPlansWrapper mediaPlansWrapperTest = new OperativeOneResponseWrapper.MediaPlansWrapper();
        OperativeOneResponseWrapper.MediaPlenWrapper mediaPlenWrapperTest = new OperativeOneResponseWrapper.MediaPlenWrapper();
        OperativeOneResponseWrapper.NamedSectionsWrapper namedSectionsWrapperTest = new OperativeOneResponseWrapper.NamedSectionsWrapper();
        OperativeOneResponseWrapper.NamedSectionWrapper namedSectionWrapperTest = new OperativeOneResponseWrapper.NamedSectionWrapper();
        OperativeOneResponseWrapper.SalesOrderLineitemsWrapper salesOrderLineitemsWrapperTest = new OperativeOneResponseWrapper.SalesOrderLineitemsWrapper();
        OperativeOneResponseWrapper.SalesOrderLineitemWrapper salesOrderLineitemWrapperTest = new OperativeOneResponseWrapper.SalesOrderLineitemWrapper();
        OperativeOneResponseWrapper.ContactWrapper contactWrapperTest = new OperativeOneResponseWrapper.ContactWrapper();
    }
}